### PR TITLE
fix: boxes layout

### PR DESCRIPTION
**Pull request by acasazza**

### CODE REVIEW

**Comment by davidfateh** [comment]
Hey @acasazza, thanks for submitting a PR. Would you mind providing a brief explanation of what the changes are accomplishing here?

**Comment by acasazza** [comment]
Hi @davidfateh, yes of course! It's a little improvement about styling of Commerce Layer UI extension. Because, now the list of products is too big.

Screen Shot 2019-10-24 at 14 58 11

After my fix it will be.

Screen Shot 2019-10-24 at 15 03 37

**Comment by acasazza** [comment]
Oh I'm sorry. I didn't see it. 😅Thanks for all

**Comment by davidfateh** [comment]
@acasazza you're all set!

**Pull request merged**
