### PR TITLE
Makes json-form-editor load before cfApi

### PR DESCRIPTION
**Pull request by lwakefield**
Loading `json-form-editor` after `api` has been initialized means you can run the example without having a connection to contentful api. Of course, this means no data will be propagated locally.

### CODE REVIEW

**Comment by DanweDE** [comment]
Hi lwakefield. Thank you for your contribution.

I am curious, what's the use-case for running the example without having a connection to the contentful API?

**Comment by lwakefield** [comment]
Hey.

Unfortunately, it has been quite a while since I worked with Contentful Extensions. From memory however, I wanted to make some changes to json-form-editor for a custom case. In order to develop, it needed to be connected to Contentful, which as you can imagine, the edit, redploy, test cycle was painful.

**Comment by lwakefield** [comment]
I'm happy for you to close this if you think that makes sense.

**Comment by jelz** [comment]
Closed, we'll revamp this extension soon.

**Pull request closed without merging**
